---
title: "P8105-HW3-zc2556"
author: "Zhe Chen"
date: "2020/10/10"
output: github_document
---

# NOAA

## Preparation

```{r, warning=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(
  theme_minimal()+
  theme(legend.position = "bottom")
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continous.fill = "viridis"
)

scale_color_discrete = scale_colour_viridis_d()
scale_fill_discrete = scale_fill_viridis_d

```


## Clean the Data

```{r, warning=FALSE}
#import clean
data("ny_noaa")

noaa = ny_noaa %>%
  janitor::clean_names()

noaa = 
  noaa %>% 
  separate(date, into = c("year", "month", "day"), convert = TRUE) %>% 
  select(
    -id, -day, -tmax
  ) %>%
  filter(
    year >=2000 & year <= 2010
  ) %>% #keep interested time interval
  drop_na(c(snow,prcp,snwd,tmin))
```

```{r}
#convert units
noaa = 
  noaa %>%  
  mutate(
      tmin = as.numeric(tmin),
      snow_mm = snow,
      snow = round(snow_mm * 0.03937 * 4) / 4) %>%
  select(
    -snow
  )
```

This dataset documented weather information from various weather stations. 

## Scatter Plot to Show the General Snowfall from 2000 to 2010

```{r}
noaa %>%
  group_by(year,month)%>%
  summarize(Snowfall = mean(snow_mm))%>%
  plot_ly(
      x = ~year, y = ~Snowfall, type = "scatter", color = ~month, alpha = 0.5)
```


## Line Plot to Show the Treand of the Extreme Snowfall from 2000 to 2010

```{r}
noaa%>%
  group_by(year)%>%
  summarize(Snowfall = max(snow_mm))%>%
  plot_ly(
      x = ~year, y = ~Snowfall, type = "scatter", 
      mode = "markers+lines",
      color = ~Snowfall, alpha = 0.5)
```

## Bar Plot to Show the Annually Average Precipitations from 2000 to 2010

```{r}
noaa%>%
  group_by(year)%>%
  summarize(Precipitation = mean(prcp))%>%
  plot_ly(
      x = ~year, y = ~Precipitation, type = "bar", 
      color = ~Precipitation, alpha = 0.5)
```











